### ISSUE TITLE
Refactor to remove jQuery

### ISSUE THREAD

**Issue by willianjusten** [willianjusten/volta-mozao#4]
Some people didn't know, but yes, I created this project in around 10min in a queue in the Airport. I didn't have time and patience to do a nice and beautiful code, I just wanted to create something really fast and working.

But yeah, we can improve this, if you want, go there =D

**Comment by jhonnymoreira** [comment]
#5 closes this issue.

**Comment by willianjusten** [comment]
Yep, I forgot to close here xD
